// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mempool.proto

package network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MempoolSyncMsg represents the messages exchanging between validators to keep
// transactions in sync. The proto definition provides the spec on the wire so
// that others can implement their mempool service in various languages.
// Mempool service is responsible for sending and receiving MempoolSyncMsg
// across validators.
type MempoolSyncMsg struct {
	PeerId               []byte               `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Transactions         []*SignedTransaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MempoolSyncMsg) Reset()         { *m = MempoolSyncMsg{} }
func (m *MempoolSyncMsg) String() string { return proto.CompactTextString(m) }
func (*MempoolSyncMsg) ProtoMessage()    {}
func (*MempoolSyncMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a84c3667d8c2093a, []int{0}
}

func (m *MempoolSyncMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MempoolSyncMsg.Unmarshal(m, b)
}
func (m *MempoolSyncMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MempoolSyncMsg.Marshal(b, m, deterministic)
}
func (m *MempoolSyncMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MempoolSyncMsg.Merge(m, src)
}
func (m *MempoolSyncMsg) XXX_Size() int {
	return xxx_messageInfo_MempoolSyncMsg.Size(m)
}
func (m *MempoolSyncMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MempoolSyncMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MempoolSyncMsg proto.InternalMessageInfo

func (m *MempoolSyncMsg) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *MempoolSyncMsg) GetTransactions() []*SignedTransaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*MempoolSyncMsg)(nil), "network.MempoolSyncMsg")
}

func init() { proto.RegisterFile("mempool.proto", fileDescriptor_a84c3667d8c2093a) }

var fileDescriptor_a84c3667d8c2093a = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0xcd, 0x2d,
	0xc8, 0xcf, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0x96, 0x12, 0x2c, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x83,
	0xc8, 0x29, 0xa5, 0x73, 0xf1, 0xf9, 0x42, 0x14, 0x07, 0x57, 0xe6, 0x25, 0xfb, 0x16, 0xa7, 0x0b,
	0x89, 0x73, 0xb1, 0x17, 0xa4, 0xa6, 0x16, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x04, 0xb1, 0x81, 0xb8, 0x9e, 0x29, 0x42, 0x36, 0x5c, 0x3c, 0x48, 0xfa, 0x8b, 0x25, 0x98, 0x14,
	0x98, 0x35, 0xb8, 0x8d, 0x24, 0xf4, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0xf5, 0x82, 0x33, 0xd3, 0xf3,
	0x52, 0x53, 0x42, 0x10, 0x0a, 0x82, 0x50, 0x54, 0x27, 0xb1, 0x81, 0xed, 0x33, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x29, 0x56, 0xa8, 0x64, 0x9c, 0x00, 0x00, 0x00,
}
