// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state_synchronizer.proto

package network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetChunkRequest struct {
	KnownVersion         uint64                    `protobuf:"varint,1,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	Limit                uint64                    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Timeout              uint64                    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	LedgerInfoWithSigs   *LedgerInfoWithSignatures `protobuf:"bytes,4,opt,name=ledger_info_with_sigs,json=ledgerInfoWithSigs,proto3" json:"ledger_info_with_sigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetChunkRequest) Reset()         { *m = GetChunkRequest{} }
func (m *GetChunkRequest) String() string { return proto.CompactTextString(m) }
func (*GetChunkRequest) ProtoMessage()    {}
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_405c68b310d50bdb, []int{0}
}

func (m *GetChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChunkRequest.Unmarshal(m, b)
}
func (m *GetChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChunkRequest.Marshal(b, m, deterministic)
}
func (m *GetChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChunkRequest.Merge(m, src)
}
func (m *GetChunkRequest) XXX_Size() int {
	return xxx_messageInfo_GetChunkRequest.Size(m)
}
func (m *GetChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChunkRequest proto.InternalMessageInfo

func (m *GetChunkRequest) GetKnownVersion() uint64 {
	if m != nil {
		return m.KnownVersion
	}
	return 0
}

func (m *GetChunkRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetChunkRequest) GetTimeout() uint64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *GetChunkRequest) GetLedgerInfoWithSigs() *LedgerInfoWithSignatures {
	if m != nil {
		return m.LedgerInfoWithSigs
	}
	return nil
}

type GetChunkResponse struct {
	LedgerInfoWithSigs *LedgerInfoWithSignatures `protobuf:"bytes,1,opt,name=ledger_info_with_sigs,json=ledgerInfoWithSigs,proto3" json:"ledger_info_with_sigs,omitempty"`
	// chunk of transactions with proof corresponding to version in `ledger_info_with_sigs`
	TxnListWithProof     *TransactionListWithProof `protobuf:"bytes,2,opt,name=txn_list_with_proof,json=txnListWithProof,proto3" json:"txn_list_with_proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetChunkResponse) Reset()         { *m = GetChunkResponse{} }
func (m *GetChunkResponse) String() string { return proto.CompactTextString(m) }
func (*GetChunkResponse) ProtoMessage()    {}
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_405c68b310d50bdb, []int{1}
}

func (m *GetChunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChunkResponse.Unmarshal(m, b)
}
func (m *GetChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChunkResponse.Marshal(b, m, deterministic)
}
func (m *GetChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChunkResponse.Merge(m, src)
}
func (m *GetChunkResponse) XXX_Size() int {
	return xxx_messageInfo_GetChunkResponse.Size(m)
}
func (m *GetChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChunkResponse proto.InternalMessageInfo

func (m *GetChunkResponse) GetLedgerInfoWithSigs() *LedgerInfoWithSignatures {
	if m != nil {
		return m.LedgerInfoWithSigs
	}
	return nil
}

func (m *GetChunkResponse) GetTxnListWithProof() *TransactionListWithProof {
	if m != nil {
		return m.TxnListWithProof
	}
	return nil
}

type StateSynchronizerMsg struct {
	// Types that are valid to be assigned to Message:
	//	*StateSynchronizerMsg_ChunkRequest
	//	*StateSynchronizerMsg_ChunkResponse
	Message              isStateSynchronizerMsg_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *StateSynchronizerMsg) Reset()         { *m = StateSynchronizerMsg{} }
func (m *StateSynchronizerMsg) String() string { return proto.CompactTextString(m) }
func (*StateSynchronizerMsg) ProtoMessage()    {}
func (*StateSynchronizerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_405c68b310d50bdb, []int{2}
}

func (m *StateSynchronizerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSynchronizerMsg.Unmarshal(m, b)
}
func (m *StateSynchronizerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSynchronizerMsg.Marshal(b, m, deterministic)
}
func (m *StateSynchronizerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSynchronizerMsg.Merge(m, src)
}
func (m *StateSynchronizerMsg) XXX_Size() int {
	return xxx_messageInfo_StateSynchronizerMsg.Size(m)
}
func (m *StateSynchronizerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSynchronizerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StateSynchronizerMsg proto.InternalMessageInfo

type isStateSynchronizerMsg_Message interface {
	isStateSynchronizerMsg_Message()
}

type StateSynchronizerMsg_ChunkRequest struct {
	ChunkRequest *GetChunkRequest `protobuf:"bytes,1,opt,name=chunk_request,json=chunkRequest,proto3,oneof"`
}

type StateSynchronizerMsg_ChunkResponse struct {
	ChunkResponse *GetChunkResponse `protobuf:"bytes,2,opt,name=chunk_response,json=chunkResponse,proto3,oneof"`
}

func (*StateSynchronizerMsg_ChunkRequest) isStateSynchronizerMsg_Message() {}

func (*StateSynchronizerMsg_ChunkResponse) isStateSynchronizerMsg_Message() {}

func (m *StateSynchronizerMsg) GetMessage() isStateSynchronizerMsg_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *StateSynchronizerMsg) GetChunkRequest() *GetChunkRequest {
	if x, ok := m.GetMessage().(*StateSynchronizerMsg_ChunkRequest); ok {
		return x.ChunkRequest
	}
	return nil
}

func (m *StateSynchronizerMsg) GetChunkResponse() *GetChunkResponse {
	if x, ok := m.GetMessage().(*StateSynchronizerMsg_ChunkResponse); ok {
		return x.ChunkResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StateSynchronizerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StateSynchronizerMsg_ChunkRequest)(nil),
		(*StateSynchronizerMsg_ChunkResponse)(nil),
	}
}

func init() {
	proto.RegisterType((*GetChunkRequest)(nil), "network.GetChunkRequest")
	proto.RegisterType((*GetChunkResponse)(nil), "network.GetChunkResponse")
	proto.RegisterType((*StateSynchronizerMsg)(nil), "network.StateSynchronizerMsg")
}

func init() { proto.RegisterFile("state_synchronizer.proto", fileDescriptor_405c68b310d50bdb) }

var fileDescriptor_405c68b310d50bdb = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xdf, 0xc7, 0xf7, 0x11, 0x57, 0x50, 0x58, 0x31, 0xa9, 0x5c, 0x24, 0x78, 0xe1, 0xd4,
	0x83, 0xfe, 0x00, 0x13, 0x3c, 0x88, 0x09, 0x1a, 0x53, 0x8c, 0x1e, 0x37, 0xb5, 0x0e, 0xed, 0x86,
	0xb2, 0x5b, 0x77, 0xa6, 0x02, 0xfe, 0x20, 0x7f, 0x82, 0x07, 0x7f, 0x9d, 0x69, 0x17, 0x42, 0x25,
	0x7a, 0xf1, 0x38, 0x6f, 0xde, 0xbe, 0x79, 0x33, 0x6f, 0x99, 0x8b, 0x14, 0x10, 0x08, 0x5c, 0xaa,
	0x30, 0x36, 0x5a, 0xc9, 0x57, 0x30, 0x5e, 0x6a, 0x34, 0x69, 0x5e, 0x53, 0x40, 0x73, 0x6d, 0xa6,
	0x9d, 0x56, 0x02, 0x4f, 0x11, 0x18, 0x21, 0xd5, 0x44, 0xdb, 0x5e, 0xa7, 0x45, 0x26, 0x50, 0x18,
	0x84, 0x24, 0xb5, 0xb2, 0x50, 0xef, 0xc3, 0x61, 0xfb, 0x97, 0x40, 0x17, 0x71, 0xa6, 0xa6, 0x3e,
	0x3c, 0x67, 0x80, 0xc4, 0x4f, 0x58, 0x63, 0xaa, 0xf4, 0x5c, 0x89, 0x17, 0x30, 0x28, 0xb5, 0x72,
	0x9d, 0xae, 0xd3, 0xaf, 0xfa, 0xf5, 0x02, 0xbc, 0xb7, 0x18, 0x6f, 0xb3, 0x7f, 0x89, 0x9c, 0x49,
	0x72, 0xff, 0x14, 0x4d, 0x5b, 0x70, 0x97, 0xd5, 0x48, 0xce, 0x40, 0x67, 0xe4, 0xfe, 0x2d, 0xf0,
	0x75, 0xc9, 0x7d, 0x76, 0x58, 0x32, 0x24, 0xe6, 0x92, 0x62, 0x81, 0x32, 0x42, 0xb7, 0xda, 0x75,
	0xfa, 0xbb, 0xa7, 0xc7, 0x1e, 0x2d, 0x53, 0x40, 0x6f, 0x54, 0x70, 0xae, 0xd4, 0x44, 0x3f, 0x48,
	0x8a, 0xc7, 0x32, 0x52, 0x01, 0x65, 0x06, 0xd0, 0xe7, 0xc9, 0x76, 0x07, 0x7b, 0xef, 0x0e, 0x6b,
	0x6e, 0xcc, 0x63, 0xaa, 0x15, 0xc2, 0xcf, 0x83, 0x9c, 0x5f, 0x0f, 0xe2, 0x37, 0xec, 0x80, 0x16,
	0x4a, 0x24, 0x12, 0xc9, 0x0a, 0xa6, 0x46, 0xeb, 0x49, 0xb1, 0xfa, 0x46, 0xf1, 0x6e, 0x73, 0xdc,
	0x91, 0x44, 0xca, 0x1f, 0xdf, 0xe6, 0x34, 0xbf, 0x49, 0x8b, 0xaf, 0x48, 0xef, 0xcd, 0x61, 0xed,
	0x71, 0x9e, 0xe0, 0xb8, 0x14, 0xe0, 0x35, 0x46, 0xfc, 0x9c, 0x35, 0xc2, 0x7c, 0x1b, 0x61, 0x6c,
	0x16, 0x2b, 0xd3, 0xae, 0xb7, 0x4a, 0xd5, 0xdb, 0xca, 0x6a, 0x58, 0xf1, 0xeb, 0x61, 0x39, 0xbb,
	0x01, 0xdb, 0x5b, 0x0b, 0xd8, 0x7b, 0xac, 0x4c, 0x1e, 0x7d, 0xa3, 0x60, 0x09, 0xc3, 0x8a, 0xdf,
	0x08, 0xcb, 0xc0, 0x60, 0x87, 0xd5, 0x66, 0x80, 0x18, 0x44, 0xf0, 0xf8, 0xbf, 0xf8, 0x25, 0x67,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0x0b, 0x79, 0x9d, 0x70, 0x02, 0x00, 0x00,
}
