// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_debug_interface.proto

package debug

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNodeDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeDetailsRequest) Reset()         { *m = GetNodeDetailsRequest{} }
func (m *GetNodeDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeDetailsRequest) ProtoMessage()    {}
func (*GetNodeDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{0}
}

func (m *GetNodeDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDetailsRequest.Unmarshal(m, b)
}
func (m *GetNodeDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDetailsRequest.Merge(m, src)
}
func (m *GetNodeDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeDetailsRequest.Size(m)
}
func (m *GetNodeDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDetailsRequest proto.InternalMessageInfo

type GetNodeDetailsResponse struct {
	Stats                map[string]string `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetNodeDetailsResponse) Reset()         { *m = GetNodeDetailsResponse{} }
func (m *GetNodeDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeDetailsResponse) ProtoMessage()    {}
func (*GetNodeDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{1}
}

func (m *GetNodeDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeDetailsResponse.Unmarshal(m, b)
}
func (m *GetNodeDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeDetailsResponse.Merge(m, src)
}
func (m *GetNodeDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeDetailsResponse.Size(m)
}
func (m *GetNodeDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeDetailsResponse proto.InternalMessageInfo

func (m *GetNodeDetailsResponse) GetStats() map[string]string {
	if m != nil {
		return m.Stats
	}
	return nil
}

type GetEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{2}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{3}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Json                 string   `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type DumpJemallocHeapProfileRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpJemallocHeapProfileRequest) Reset()         { *m = DumpJemallocHeapProfileRequest{} }
func (m *DumpJemallocHeapProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DumpJemallocHeapProfileRequest) ProtoMessage()    {}
func (*DumpJemallocHeapProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{5}
}

func (m *DumpJemallocHeapProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Unmarshal(m, b)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Marshal(b, m, deterministic)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpJemallocHeapProfileRequest.Merge(m, src)
}
func (m *DumpJemallocHeapProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DumpJemallocHeapProfileRequest.Size(m)
}
func (m *DumpJemallocHeapProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpJemallocHeapProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpJemallocHeapProfileRequest proto.InternalMessageInfo

type DumpJemallocHeapProfileResponse struct {
	// Status code from jemalloc mallctl call. 0 indicates success.
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpJemallocHeapProfileResponse) Reset()         { *m = DumpJemallocHeapProfileResponse{} }
func (m *DumpJemallocHeapProfileResponse) String() string { return proto.CompactTextString(m) }
func (*DumpJemallocHeapProfileResponse) ProtoMessage()    {}
func (*DumpJemallocHeapProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44a3c1322867efb7, []int{6}
}

func (m *DumpJemallocHeapProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Unmarshal(m, b)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Marshal(b, m, deterministic)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpJemallocHeapProfileResponse.Merge(m, src)
}
func (m *DumpJemallocHeapProfileResponse) XXX_Size() int {
	return xxx_messageInfo_DumpJemallocHeapProfileResponse.Size(m)
}
func (m *DumpJemallocHeapProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpJemallocHeapProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpJemallocHeapProfileResponse proto.InternalMessageInfo

func (m *DumpJemallocHeapProfileResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNodeDetailsRequest)(nil), "debug.GetNodeDetailsRequest")
	proto.RegisterType((*GetNodeDetailsResponse)(nil), "debug.GetNodeDetailsResponse")
	proto.RegisterMapType((map[string]string)(nil), "debug.GetNodeDetailsResponse.StatsEntry")
	proto.RegisterType((*GetEventsRequest)(nil), "debug.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "debug.GetEventsResponse")
	proto.RegisterType((*Event)(nil), "debug.Event")
	proto.RegisterType((*DumpJemallocHeapProfileRequest)(nil), "debug.DumpJemallocHeapProfileRequest")
	proto.RegisterType((*DumpJemallocHeapProfileResponse)(nil), "debug.DumpJemallocHeapProfileResponse")
}

func init() { proto.RegisterFile("node_debug_interface.proto", fileDescriptor_44a3c1322867efb7) }

var fileDescriptor_44a3c1322867efb7 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x2d, 0xb5, 0x24, 0x0c, 0xc6, 0xe0, 0x46, 0xa5, 0x69, 0x50, 0x48, 0xa3, 0x86, 0x53,
	0x0f, 0x78, 0x41, 0x0f, 0xc6, 0x28, 0x04, 0x35, 0xf1, 0x4f, 0xea, 0x03, 0x90, 0x85, 0x0e, 0xa4,
	0xd8, 0x76, 0x6b, 0x77, 0x4b, 0xc2, 0x6b, 0xe8, 0x0b, 0x9b, 0x6e, 0x17, 0x10, 0x15, 0xbc, 0x4d,
	0xbf, 0xf9, 0x66, 0xfa, 0xeb, 0x37, 0x05, 0x2b, 0x62, 0x1e, 0xf6, 0x3d, 0x1c, 0xa4, 0xe3, 0xbe,
	0x1f, 0x09, 0x4c, 0x46, 0x74, 0x88, 0x4e, 0x9c, 0x30, 0xc1, 0x88, 0x21, 0x65, 0xbb, 0x0a, 0x07,
	0x3d, 0x14, 0x4f, 0xcc, 0xc3, 0x0e, 0x0a, 0xea, 0x07, 0xdc, 0xc5, 0xf7, 0x14, 0xb9, 0xb0, 0x3f,
	0x34, 0x38, 0xfc, 0xd9, 0xe1, 0x31, 0x8b, 0x38, 0x92, 0x2b, 0x30, 0xb8, 0xa0, 0x82, 0x9b, 0x5a,
	0x43, 0x6f, 0x96, 0x5b, 0x4d, 0x47, 0xae, 0x72, 0xfe, 0x76, 0x3b, 0xaf, 0x99, 0xb5, 0x1b, 0x89,
	0x64, 0xe6, 0xe6, 0x63, 0x56, 0x1b, 0x60, 0x29, 0x92, 0x0a, 0xe8, 0x6f, 0x38, 0x33, 0xb5, 0x86,
	0xd6, 0x2c, 0xb9, 0x59, 0x49, 0xf6, 0xc1, 0x98, 0xd2, 0x20, 0x45, 0xb3, 0x20, 0xb5, 0xfc, 0xe1,
	0xb2, 0xd0, 0xd6, 0x6c, 0x02, 0x95, 0x1e, 0x8a, 0xee, 0x14, 0x23, 0xb1, 0x00, 0xbd, 0x80, 0xbd,
	0x6f, 0x9a, 0x42, 0x3c, 0x81, 0x22, 0x4a, 0x45, 0x31, 0xee, 0x28, 0x46, 0x69, 0x73, 0x55, 0xcf,
	0x7e, 0x04, 0x43, 0x0a, 0x84, 0xc0, 0x76, 0x44, 0x43, 0x54, 0x10, 0xb2, 0x26, 0x35, 0x28, 0x09,
	0x3f, 0x44, 0x2e, 0x68, 0x18, 0x4b, 0x12, 0xdd, 0x5d, 0x0a, 0xd9, 0xc4, 0x84, 0xb3, 0xc8, 0xd4,
	0xf3, 0x89, 0xac, 0xb6, 0x1b, 0x70, 0xdc, 0x49, 0xc3, 0xf8, 0x01, 0x43, 0x1a, 0x04, 0x6c, 0x78,
	0x87, 0x34, 0x7e, 0x49, 0xd8, 0xc8, 0x0f, 0x70, 0xce, 0x7a, 0x03, 0xf5, 0xb5, 0x0e, 0x45, 0x5e,
	0x87, 0x72, 0x96, 0x52, 0xca, 0xfb, 0x43, 0xe6, 0xe5, 0x44, 0x86, 0x0b, 0xb9, 0x74, 0xcb, 0x3c,
	0x6c, 0x7d, 0x16, 0x80, 0xe4, 0x39, 0x0f, 0xd2, 0xf1, 0xfd, 0xfc, 0xaa, 0xe4, 0x19, 0x76, 0x57,
	0x0f, 0x40, 0x6a, 0x6b, 0xee, 0x22, 0x51, 0xac, 0xa3, 0x8d, 0x57, 0xb3, 0xb7, 0xc8, 0x35, 0x94,
	0x16, 0xb9, 0x92, 0xea, 0xd2, 0xbd, 0x92, 0xbe, 0x65, 0xfe, 0x6e, 0x2c, 0x36, 0x4c, 0xa0, 0xba,
	0xe6, 0x6b, 0xc9, 0xa9, 0x1a, 0xdb, 0x9c, 0x97, 0x75, 0xf6, 0x9f, 0x6d, 0xfe, 0xae, 0x41, 0x51,
	0xfe, 0xd5, 0xe7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf0, 0x0c, 0x32, 0xf3, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeDebugInterfaceClient is the client API for NodeDebugInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeDebugInterfaceClient interface {
	// Returns debug information about node
	GetNodeDetails(ctx context.Context, in *GetNodeDetailsRequest, opts ...grpc.CallOption) (*GetNodeDetailsResponse, error)
	// Returns recent events generated by event! macro
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	// Triggers a dump of heap profile.
	DumpJemallocHeapProfile(ctx context.Context, in *DumpJemallocHeapProfileRequest, opts ...grpc.CallOption) (*DumpJemallocHeapProfileResponse, error)
}

type nodeDebugInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewNodeDebugInterfaceClient(cc *grpc.ClientConn) NodeDebugInterfaceClient {
	return &nodeDebugInterfaceClient{cc}
}

func (c *nodeDebugInterfaceClient) GetNodeDetails(ctx context.Context, in *GetNodeDetailsRequest, opts ...grpc.CallOption) (*GetNodeDetailsResponse, error) {
	out := new(GetNodeDetailsResponse)
	err := c.cc.Invoke(ctx, "/debug.NodeDebugInterface/GetNodeDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeDebugInterfaceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/debug.NodeDebugInterface/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeDebugInterfaceClient) DumpJemallocHeapProfile(ctx context.Context, in *DumpJemallocHeapProfileRequest, opts ...grpc.CallOption) (*DumpJemallocHeapProfileResponse, error) {
	out := new(DumpJemallocHeapProfileResponse)
	err := c.cc.Invoke(ctx, "/debug.NodeDebugInterface/DumpJemallocHeapProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeDebugInterfaceServer is the server API for NodeDebugInterface service.
type NodeDebugInterfaceServer interface {
	// Returns debug information about node
	GetNodeDetails(context.Context, *GetNodeDetailsRequest) (*GetNodeDetailsResponse, error)
	// Returns recent events generated by event! macro
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	// Triggers a dump of heap profile.
	DumpJemallocHeapProfile(context.Context, *DumpJemallocHeapProfileRequest) (*DumpJemallocHeapProfileResponse, error)
}

// UnimplementedNodeDebugInterfaceServer can be embedded to have forward compatible implementations.
type UnimplementedNodeDebugInterfaceServer struct {
}

func (*UnimplementedNodeDebugInterfaceServer) GetNodeDetails(ctx context.Context, req *GetNodeDetailsRequest) (*GetNodeDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeDetails not implemented")
}
func (*UnimplementedNodeDebugInterfaceServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedNodeDebugInterfaceServer) DumpJemallocHeapProfile(ctx context.Context, req *DumpJemallocHeapProfileRequest) (*DumpJemallocHeapProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpJemallocHeapProfile not implemented")
}

func RegisterNodeDebugInterfaceServer(s *grpc.Server, srv NodeDebugInterfaceServer) {
	s.RegisterService(&_NodeDebugInterface_serviceDesc, srv)
}

func _NodeDebugInterface_GetNodeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeDebugInterfaceServer).GetNodeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debug.NodeDebugInterface/GetNodeDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeDebugInterfaceServer).GetNodeDetails(ctx, req.(*GetNodeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeDebugInterface_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeDebugInterfaceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debug.NodeDebugInterface/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeDebugInterfaceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeDebugInterface_DumpJemallocHeapProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpJemallocHeapProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeDebugInterfaceServer).DumpJemallocHeapProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debug.NodeDebugInterface/DumpJemallocHeapProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeDebugInterfaceServer).DumpJemallocHeapProfile(ctx, req.(*DumpJemallocHeapProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeDebugInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "debug.NodeDebugInterface",
	HandlerType: (*NodeDebugInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeDetails",
			Handler:    _NodeDebugInterface_GetNodeDetails_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _NodeDebugInterface_GetEvents_Handler,
		},
		{
			MethodName: "DumpJemallocHeapProfile",
			Handler:    _NodeDebugInterface_DumpJemallocHeapProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_debug_interface.proto",
}
